services:
  minio:
    image: minio/minio
    ports: ["9005:9000", "9001:9001"]
    environment:
      MINIO_BROWSER: "on"
      MINIO_DOMAIN: localhost
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

  # THIS NAME MUST MATCH
  transcoder:
    build: ./services/transcoder-worker
    volumes:
      - ./uploads:/app/uploads
      - ./video_output:/app/video_output

  gateway:
    image: nginx:alpine
    ports: ["9000:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./video_output:/usr/share/nginx/html/video:ro
